### ISSUE TITLE
Add note in dissect filter docs for Logstash 5.5

### ISSUE THREAD

**Issue by acchen97** [logstash-plugins/logstash-filter-dissect#31]
We have a bug that impacts the default dissect filter plugin that's bundled with Logstash 5.5.0. This issue should be resolved in 5.5.1 and greater. Let's add a note addressing this in the 5.5 version of the docs:

```
Note: the Logstash 5.5.0 release will not work with the dissect filter out-of-the-box. To use this plugin, please uninstall and reinstall the dissect filter to v1.0.11 or higher.

bin/logstash-plugin update logstash-filter-dissect
```

**Comment by dedemorton** [comment]
@acchen97 Based on recent discussion on slack, I'm adding this note:

The Logstash 5.5.0 release will not work with the dissect filter out-of-the-box. To use this plugin, please update the dissect filter to v1.0.11 or higher by running:

`bin/logstash-plugin update logstash-filter-dissect`

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/logstash-docs/pull/402
