### ISSUE TITLE
Mapping Doesnt Support > 2 key/value pairs

### ISSUE THREAD

**Issue by preiner** [logstash-plugins/logstash-filter-dissect#36]
I have a multi-line log file coming in from filebeat to logstash (each event is 21 lines long). For ease discussion, I have simplified the problem as much as possible. I have also replaced every \n with # char to ease readability.

My goal is to end up with a var holding all chars up to a # (this basically means one var per line)
However no matter what I do, I can only get 2 keys to work (for ex: message and rest). when I add additional keys, I always get a key not found error and I notice that the interpretation isnt occuring in order. (Almost like each mapping line is its own thread and Im running into a race condition)

I know in theory  I could have all of it in one HUGE message string, but thats unreadable. and if I try to use \ as a line continuation char, dissect doesnt function properly.

So, my ask is how do I get multiple key/value pairs to function?

My dissect snippet is as follows:
      dissect {
        mapping => {
          "message" =>%{line1}#%{rest}"
          "rest" => "%{line2}#%{rest2}"
          "rest2" => "%{line3}#%{rest3}"
          "rest3" => "%{line4}#%{rest4}"
          }
        }

**Comment by guyboertje** [comment]
This is a call for help and not a bug report, please move this discussion to our discuss forum to make it easier for other users to see the problem and help or see the solution.
https://discuss.elastic.co/c/logstash
