### ISSUE TITLE
Install the new version 1.1.1, that report the ERROR

### ISSUE THREAD

**Issue by qianghaohao** [logstash-plugins/logstash-filter-dissect#45]
@guyboertje @colinsurprenant 
It seems that missing the jar files!
I just want to install the new version 1.1.1 of dissect, followed the instruction of README.md, but that failed, when i start logstash then it reported ERROR as following:
> [2017-11-01T21:17:18,053][ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"filter", :name=>"dissect", :path=>"logstash/filters/dissect", :error_message=>"\n\n\tyou might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command\n\nno such file to load -- org/logstash/dissect/jruby-dissect-library/1.1.1/jruby-dissect-library-1.1.1 (LoadError)", :error_class=>RuntimeError, :error_backtrace=>["/home/web/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jar_dependencies.rb:348:in `do_require'", "/home/web/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jar_dependencies.rb:255:in `require_jar'", "/home/web/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jar_dependencies.rb:0:in `require_jar_with_block'", "/home/web/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jar_dependencies.rb:254:in `require_jar'", "/home/web/logstash-5.5.1/lib/bootstrap/patches/jar_dependencies.rb:6:in `require_jar'", "/home/web/logstash-filter-dissect/lib/jruby-dissect-library_jars.rb:4:in `(root)'", "org/jruby/RubyKernel.java:1040:in `require'", "/home/web/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/home/web/logstash-filter-dissect/lib/logstash/filters/dissect.rb:1:in `(root)'", "org/jruby/RubyKernel.java:1040:in `require'", "/home/web/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/home/web/logstash-filter-dissect/lib/logstash/filters/dissect.rb:6:in `(root)'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/plugins/registry.rb:1:in `(root)'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/plugins/registry.rb:156:in `legacy_lookup'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/plugins/registry.rb:138:in `lookup'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/plugins/registry.rb:180:in `lookup_pipeline_plugin'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/plugin.rb:140:in `lookup'", "org/jruby/RubyKernel.java:1079:in `eval'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/pipeline.rb:100:in `plugin'", "(eval):37:in `initialize'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/pipeline.rb:72:in `initialize'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/pipeline.rb:156:in `initialize'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/agent.rb:286:in `create_pipeline'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/agent.rb:95:in `register_pipeline'", "/home/web/logstash-5.5.1/logstash-core/lib/logstash/runner.rb:314:in `execute'", "/home/web/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/home/web/logstash-5.5.1/lib/bootstrap/environment.rb:71:in `(root)'"]}

**The following is my installation steps:**
- bin/logstash-plugin remove logstash-filter-dissect
- git clone https://github.com/logstash-plugins/logstash-filter-dissect.git
- cd logstash-filter-dissect
- gem build logstash-filter-dissect-1.1.1.gem
- bin/logstash-plugin install --no-verify
- bin/logstah -f config/central
----
**Related Information**
- Logstash Version: 5.5.1
- Operating System: CentOS 7
- Part of Gemfile:
>gem "logstash-filter-dissect", :path => "/home/web/logstash-filter-dissect"

**Comment by qianghaohao** [comment]
**In the following way, i installed the version 1.1.1, still report the same ERROR**
```bin/logstash-plugin install /home/web/logstash-filter-dissect/logstash-filter-dissect-1.1.1.gem```
**The plugin is install successfully, but not work:**
`[web@awsuw21-90 logstash-5.5.1]$ bin/logstash-plugin list --verbose | grep dissect
logstash-filter-dissect (1.1.1)`

**Comment by qianghaohao** [comment]
It sames that missing the jar file：
>[web@awsuw21-90 logstash-5.5.1]$ find . -name "jruby-dissect-library*" -print
./vendor/bundle/jruby/1.9/gems/logstash-filter-dissect-1.0.11/lib/jruby-dissect-library_jars.rb
./vendor/bundle/jruby/1.9/gems/logstash-filter-dissect-1.0.11/vendor/jars/org/logstash/dissect/jruby-dissect-library
./vendor/bundle/jruby/1.9/gems/logstash-filter-dissect-1.0.11/vendor/jars/org/logstash/dissect/jruby-dissect-library/1.0.11/jruby-dissect-library-1.0.11.jar
./vendor/bundle/jruby/1.9/gems/logstash-filter-dissect-1.0.12/lib/jruby-dissect-library_jars.rb
./vendor/bundle/jruby/1.9/gems/logstash-filter-dissect-1.0.12/vendor/jars/org/logstash/dissect/jruby-dissect-library
./vendor/bundle/jruby/1.9/gems/logstash-filter-dissect-1.0.12/vendor/jars/org/logstash/dissect/jruby-dissect-library/1.0.12/jruby-dissect-library-1.0.12.jar
./vendor/local_gems/95f157c3/logstash-filter-dissect-1.1.1/lib/jruby-dissect-library_jars.rb

**Comment by guyboertje** [comment]
@qianghaohao 

version 1.1.1 was released to rubygems earlier today.

For reference (file `ci/build.sh` has clues):
```shell
    bundle install
    bundle exec rake vendor # <- this is the command that compiles the jar and puts it in the vendor folder
    gem build ./logstash-filter-dissect.gemspec
    gem install ./logstash-filter-dissect-1.1.1.gem
```

**Comment by qianghaohao** [comment]
@guyboertje Thank you very much. I download the gem package from the RubyGem.org and installed successfully.
`bin/logstash-plugin install ../logstash-filter-dissect-1.1.1.gem`
