### ISSUE TITLE
Publish as standalone-library in Maven

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-filter-dissect#58]
It would be nice to re-use Dissect in other applications, like Elasticsearch.

Without copying code, it would make sense to me to introduce a new Elasticsearch Ingest Plugin that will depend on this shared library

let me know your thoughts @guyboertje!

**Comment by guyboertje** [comment]
@talevy 
Yes. That is the plan. First, we need to unify behaviour between beats impl and ours. Second, beats + LS need to implement the multiple patterns proposal. Third, create Maven artifact.

**Comment by jakelandis** [comment]
@guyboertje - Any issues if we change the order : 

1. create Maven artifact
2. update LS to use Maven artifact
3. create ES ingest node using the Maven artifact
4. work towards unification with beats 
5. implement multiple patterns proposal 

I would like to start working on 1,2,3 assuming no objections.

**Comment by guyboertje** [comment]
@jakelandis 
Let me show what I have done last week and then we should decide.

**Comment by guyboertje** [comment]
Closing. As discussed with @jakelandis, ES will not use the LS implementation - so no point in publishing to maven.
